// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gRPC/DestinationbardCommunicationAPI.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

/// <summary>
/// 行先ボード通信API
/// </summary>
public static partial class DestinationbardCommunicationAPI
{
  static readonly string __ServiceName = "DestinationbardCommunicationAPI";

  static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (message is global::Google.Protobuf.IBufferMessage)
    {
      context.SetPayloadLength(message.CalculateSize());
      global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
      context.Complete();
      return;
    }
    #endif
    context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
  }

  static class __Helper_MessageCache<T>
  {
    public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
  }

  static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (__Helper_MessageCache<T>.IsBufferMessage)
    {
      return parser.ParseFrom(context.PayloadAsReadOnlySequence());
    }
    #endif
    return parser.ParseFrom(context.PayloadAsNewBuffer());
  }

  static readonly grpc::Marshaller<global::GetStaffsRequest> __Marshaller_GetStaffsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GetStaffsRequest.Parser));
  static readonly grpc::Marshaller<global::GetStaffsReply> __Marshaller_GetStaffsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GetStaffsReply.Parser));
  static readonly grpc::Marshaller<global::RegistStaffRequest> __Marshaller_RegistStaffRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RegistStaffRequest.Parser));
  static readonly grpc::Marshaller<global::RegistStaffReply> __Marshaller_RegistStaffReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RegistStaffReply.Parser));
  static readonly grpc::Marshaller<global::GetActionsRequest> __Marshaller_GetActionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GetActionsRequest.Parser));
  static readonly grpc::Marshaller<global::GetActionsReply> __Marshaller_GetActionsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GetActionsReply.Parser));
  static readonly grpc::Marshaller<global::RegistActionsRequest> __Marshaller_RegistActionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RegistActionsRequest.Parser));
  static readonly grpc::Marshaller<global::RegistActionsReply> __Marshaller_RegistActionsReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RegistActionsReply.Parser));
  static readonly grpc::Marshaller<global::RegistActionPlansRequest> __Marshaller_RegistActionPlansRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RegistActionPlansRequest.Parser));
  static readonly grpc::Marshaller<global::RegistActionPlansReply> __Marshaller_RegistActionPlansReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RegistActionPlansReply.Parser));
  static readonly grpc::Marshaller<global::GetActionPlansRequest> __Marshaller_GetActionPlansRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GetActionPlansRequest.Parser));
  static readonly grpc::Marshaller<global::GetActionPlansReply> __Marshaller_GetActionPlansReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GetActionPlansReply.Parser));
  static readonly grpc::Marshaller<global::StaffMasterRequest> __Marshaller_StaffMasterRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::StaffMasterRequest.Parser));
  static readonly grpc::Marshaller<global::StaffMasterReply> __Marshaller_StaffMasterReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::StaffMasterReply.Parser));
  static readonly grpc::Marshaller<global::ActionMasterRequest> __Marshaller_ActionMasterRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ActionMasterRequest.Parser));
  static readonly grpc::Marshaller<global::ActionMasterReply> __Marshaller_ActionMasterReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ActionMasterReply.Parser));
  static readonly grpc::Marshaller<global::DestinationMasterRequest> __Marshaller_DestinationMasterRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DestinationMasterRequest.Parser));
  static readonly grpc::Marshaller<global::DestinationMasterReply> __Marshaller_DestinationMasterReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DestinationMasterReply.Parser));
  static readonly grpc::Marshaller<global::ActionPlanTableRequest> __Marshaller_ActionPlanTableRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ActionPlanTableRequest.Parser));
  static readonly grpc::Marshaller<global::ActionPlanTableReply> __Marshaller_ActionPlanTableReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ActionPlanTableReply.Parser));

  static readonly grpc::Method<global::GetStaffsRequest, global::GetStaffsReply> __Method_GetStaffs = new grpc::Method<global::GetStaffsRequest, global::GetStaffsReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetStaffs",
      __Marshaller_GetStaffsRequest,
      __Marshaller_GetStaffsReply);

  static readonly grpc::Method<global::RegistStaffRequest, global::RegistStaffReply> __Method_RegistStaff = new grpc::Method<global::RegistStaffRequest, global::RegistStaffReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RegistStaff",
      __Marshaller_RegistStaffRequest,
      __Marshaller_RegistStaffReply);

  static readonly grpc::Method<global::GetActionsRequest, global::GetActionsReply> __Method_GetActions = new grpc::Method<global::GetActionsRequest, global::GetActionsReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetActions",
      __Marshaller_GetActionsRequest,
      __Marshaller_GetActionsReply);

  static readonly grpc::Method<global::RegistActionsRequest, global::RegistActionsReply> __Method_RegistActions = new grpc::Method<global::RegistActionsRequest, global::RegistActionsReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RegistActions",
      __Marshaller_RegistActionsRequest,
      __Marshaller_RegistActionsReply);

  static readonly grpc::Method<global::RegistActionPlansRequest, global::RegistActionPlansReply> __Method_RegistActionPlans = new grpc::Method<global::RegistActionPlansRequest, global::RegistActionPlansReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RegistActionPlans",
      __Marshaller_RegistActionPlansRequest,
      __Marshaller_RegistActionPlansReply);

  static readonly grpc::Method<global::GetActionPlansRequest, global::GetActionPlansReply> __Method_GetActionPlans = new grpc::Method<global::GetActionPlansRequest, global::GetActionPlansReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GetActionPlans",
      __Marshaller_GetActionPlansRequest,
      __Marshaller_GetActionPlansReply);

  static readonly grpc::Method<global::StaffMasterRequest, global::StaffMasterReply> __Method_StaffMaster = new grpc::Method<global::StaffMasterRequest, global::StaffMasterReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "StaffMaster",
      __Marshaller_StaffMasterRequest,
      __Marshaller_StaffMasterReply);

  static readonly grpc::Method<global::ActionMasterRequest, global::ActionMasterReply> __Method_ActionMaster = new grpc::Method<global::ActionMasterRequest, global::ActionMasterReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "ActionMaster",
      __Marshaller_ActionMasterRequest,
      __Marshaller_ActionMasterReply);

  static readonly grpc::Method<global::DestinationMasterRequest, global::DestinationMasterReply> __Method_DestinationMaster = new grpc::Method<global::DestinationMasterRequest, global::DestinationMasterReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "DestinationMaster",
      __Marshaller_DestinationMasterRequest,
      __Marshaller_DestinationMasterReply);

  static readonly grpc::Method<global::ActionPlanTableRequest, global::ActionPlanTableReply> __Method_ActionPlanTable = new grpc::Method<global::ActionPlanTableRequest, global::ActionPlanTableReply>(
      grpc::MethodType.Unary,
      __ServiceName,
      "ActionPlanTable",
      __Marshaller_ActionPlanTableRequest,
      __Marshaller_ActionPlanTableReply);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::DestinationbardCommunicationAPIReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of DestinationbardCommunicationAPI</summary>
  [grpc::BindServiceMethod(typeof(DestinationbardCommunicationAPI), "BindService")]
  public abstract partial class DestinationbardCommunicationAPIBase
  {
    /// <summary>
    /// 登録スタッフ情報の取得API
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::GetStaffsReply> GetStaffs(global::GetStaffsRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// スタッフ情報の登録
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::RegistStaffReply> RegistStaff(global::RegistStaffRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// 行動一覧の取得
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::GetActionsReply> GetActions(global::GetActionsRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// 行動一覧の更新
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::RegistActionsReply> RegistActions(global::RegistActionsRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// 行動予定の登録
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::RegistActionPlansReply> RegistActionPlans(global::RegistActionPlansRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::GetActionPlansReply> GetActionPlans(global::GetActionPlansRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// スタッフマスター
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::StaffMasterReply> StaffMaster(global::StaffMasterRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// 行動マスター
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::ActionMasterReply> ActionMaster(global::ActionMasterRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// 行先マスター
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::DestinationMasterReply> DestinationMaster(global::DestinationMasterRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request received from the client.</param>
    /// <param name="context">The context of the server-side call handler being invoked.</param>
    /// <returns>The response to send back to the client (wrapped by a task).</returns>
    public virtual global::System.Threading.Tasks.Task<global::ActionPlanTableReply> ActionPlanTable(global::ActionPlanTableRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for DestinationbardCommunicationAPI</summary>
  public partial class DestinationbardCommunicationAPIClient : grpc::ClientBase<DestinationbardCommunicationAPIClient>
  {
    /// <summary>Creates a new client for DestinationbardCommunicationAPI</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public DestinationbardCommunicationAPIClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for DestinationbardCommunicationAPI that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public DestinationbardCommunicationAPIClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected DestinationbardCommunicationAPIClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected DestinationbardCommunicationAPIClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    /// <summary>
    /// 登録スタッフ情報の取得API
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::GetStaffsReply GetStaffs(global::GetStaffsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetStaffs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 登録スタッフ情報の取得API
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::GetStaffsReply GetStaffs(global::GetStaffsRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetStaffs, null, options, request);
    }
    /// <summary>
    /// 登録スタッフ情報の取得API
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::GetStaffsReply> GetStaffsAsync(global::GetStaffsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetStaffsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 登録スタッフ情報の取得API
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::GetStaffsReply> GetStaffsAsync(global::GetStaffsRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetStaffs, null, options, request);
    }
    /// <summary>
    /// スタッフ情報の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::RegistStaffReply RegistStaff(global::RegistStaffRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RegistStaff(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// スタッフ情報の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::RegistStaffReply RegistStaff(global::RegistStaffRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RegistStaff, null, options, request);
    }
    /// <summary>
    /// スタッフ情報の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::RegistStaffReply> RegistStaffAsync(global::RegistStaffRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RegistStaffAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// スタッフ情報の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::RegistStaffReply> RegistStaffAsync(global::RegistStaffRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RegistStaff, null, options, request);
    }
    /// <summary>
    /// 行動一覧の取得
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::GetActionsReply GetActions(global::GetActionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetActions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動一覧の取得
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::GetActionsReply GetActions(global::GetActionsRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetActions, null, options, request);
    }
    /// <summary>
    /// 行動一覧の取得
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::GetActionsReply> GetActionsAsync(global::GetActionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetActionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動一覧の取得
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::GetActionsReply> GetActionsAsync(global::GetActionsRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetActions, null, options, request);
    }
    /// <summary>
    /// 行動一覧の更新
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::RegistActionsReply RegistActions(global::RegistActionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RegistActions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動一覧の更新
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::RegistActionsReply RegistActions(global::RegistActionsRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RegistActions, null, options, request);
    }
    /// <summary>
    /// 行動一覧の更新
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::RegistActionsReply> RegistActionsAsync(global::RegistActionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RegistActionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動一覧の更新
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::RegistActionsReply> RegistActionsAsync(global::RegistActionsRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RegistActions, null, options, request);
    }
    /// <summary>
    /// 行動予定の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::RegistActionPlansReply RegistActionPlans(global::RegistActionPlansRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RegistActionPlans(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動予定の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::RegistActionPlansReply RegistActionPlans(global::RegistActionPlansRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RegistActionPlans, null, options, request);
    }
    /// <summary>
    /// 行動予定の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::RegistActionPlansReply> RegistActionPlansAsync(global::RegistActionPlansRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RegistActionPlansAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動予定の登録
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::RegistActionPlansReply> RegistActionPlansAsync(global::RegistActionPlansRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RegistActionPlans, null, options, request);
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::GetActionPlansReply GetActionPlans(global::GetActionPlansRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetActionPlans(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::GetActionPlansReply GetActionPlans(global::GetActionPlansRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GetActionPlans, null, options, request);
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::GetActionPlansReply> GetActionPlansAsync(global::GetActionPlansRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GetActionPlansAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::GetActionPlansReply> GetActionPlansAsync(global::GetActionPlansRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GetActionPlans, null, options, request);
    }
    /// <summary>
    /// スタッフマスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::StaffMasterReply StaffMaster(global::StaffMasterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return StaffMaster(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// スタッフマスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::StaffMasterReply StaffMaster(global::StaffMasterRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_StaffMaster, null, options, request);
    }
    /// <summary>
    /// スタッフマスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::StaffMasterReply> StaffMasterAsync(global::StaffMasterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return StaffMasterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// スタッフマスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::StaffMasterReply> StaffMasterAsync(global::StaffMasterRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_StaffMaster, null, options, request);
    }
    /// <summary>
    /// 行動マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::ActionMasterReply ActionMaster(global::ActionMasterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ActionMaster(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::ActionMasterReply ActionMaster(global::ActionMasterRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_ActionMaster, null, options, request);
    }
    /// <summary>
    /// 行動マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::ActionMasterReply> ActionMasterAsync(global::ActionMasterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ActionMasterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行動マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::ActionMasterReply> ActionMasterAsync(global::ActionMasterRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_ActionMaster, null, options, request);
    }
    /// <summary>
    /// 行先マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::DestinationMasterReply DestinationMaster(global::DestinationMasterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return DestinationMaster(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行先マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::DestinationMasterReply DestinationMaster(global::DestinationMasterRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_DestinationMaster, null, options, request);
    }
    /// <summary>
    /// 行先マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::DestinationMasterReply> DestinationMasterAsync(global::DestinationMasterRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return DestinationMasterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 行先マスター
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::DestinationMasterReply> DestinationMasterAsync(global::DestinationMasterRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_DestinationMaster, null, options, request);
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::ActionPlanTableReply ActionPlanTable(global::ActionPlanTableRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ActionPlanTable(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The response received from the server.</returns>
    public virtual global::ActionPlanTableReply ActionPlanTable(global::ActionPlanTableRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_ActionPlanTable, null, options, request);
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
    /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
    /// <param name="cancellationToken">An optional token for canceling the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::ActionPlanTableReply> ActionPlanTableAsync(global::ActionPlanTableRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ActionPlanTableAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    /// <summary>
    /// 現在の行動予定一覧表
    /// </summary>
    /// <param name="request">The request to send to the server.</param>
    /// <param name="options">The options for the call.</param>
    /// <returns>The call object.</returns>
    public virtual grpc::AsyncUnaryCall<global::ActionPlanTableReply> ActionPlanTableAsync(global::ActionPlanTableRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_ActionPlanTable, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override DestinationbardCommunicationAPIClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new DestinationbardCommunicationAPIClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(DestinationbardCommunicationAPIBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_GetStaffs, serviceImpl.GetStaffs)
        .AddMethod(__Method_RegistStaff, serviceImpl.RegistStaff)
        .AddMethod(__Method_GetActions, serviceImpl.GetActions)
        .AddMethod(__Method_RegistActions, serviceImpl.RegistActions)
        .AddMethod(__Method_RegistActionPlans, serviceImpl.RegistActionPlans)
        .AddMethod(__Method_GetActionPlans, serviceImpl.GetActionPlans)
        .AddMethod(__Method_StaffMaster, serviceImpl.StaffMaster)
        .AddMethod(__Method_ActionMaster, serviceImpl.ActionMaster)
        .AddMethod(__Method_DestinationMaster, serviceImpl.DestinationMaster)
        .AddMethod(__Method_ActionPlanTable, serviceImpl.ActionPlanTable).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, DestinationbardCommunicationAPIBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_GetStaffs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GetStaffsRequest, global::GetStaffsReply>(serviceImpl.GetStaffs));
    serviceBinder.AddMethod(__Method_RegistStaff, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RegistStaffRequest, global::RegistStaffReply>(serviceImpl.RegistStaff));
    serviceBinder.AddMethod(__Method_GetActions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GetActionsRequest, global::GetActionsReply>(serviceImpl.GetActions));
    serviceBinder.AddMethod(__Method_RegistActions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RegistActionsRequest, global::RegistActionsReply>(serviceImpl.RegistActions));
    serviceBinder.AddMethod(__Method_RegistActionPlans, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RegistActionPlansRequest, global::RegistActionPlansReply>(serviceImpl.RegistActionPlans));
    serviceBinder.AddMethod(__Method_GetActionPlans, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GetActionPlansRequest, global::GetActionPlansReply>(serviceImpl.GetActionPlans));
    serviceBinder.AddMethod(__Method_StaffMaster, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::StaffMasterRequest, global::StaffMasterReply>(serviceImpl.StaffMaster));
    serviceBinder.AddMethod(__Method_ActionMaster, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ActionMasterRequest, global::ActionMasterReply>(serviceImpl.ActionMaster));
    serviceBinder.AddMethod(__Method_DestinationMaster, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DestinationMasterRequest, global::DestinationMasterReply>(serviceImpl.DestinationMaster));
    serviceBinder.AddMethod(__Method_ActionPlanTable, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ActionPlanTableRequest, global::ActionPlanTableReply>(serviceImpl.ActionPlanTable));
  }

}
#endregion
